name: Deploy Master

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH Keys and known_hosts
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        echo "${{ secrets.DEPLOY_HOST_KEY }}" >> ~/.ssh/known_hosts

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pwd
        pip install -r requirements.txt

    - name: Build the blog
      run: nikola build

    - name: Deploy the blog
      run: |
        chmod +x ./deploy-blog.sh
        ./deploy-blog.sh
