name: Deploy Master

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup SSH Keys and known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        echo "${{ secrets.DEPLOY_HOST_KEY }}" >> ~/.ssh/known_hosts

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pwd
        pip install -r requirements.txt

    - name: Build the blog
      run: nikola build

    - name: Deploy the blog
      run: |
        chmod +x ./deploy-blog.sh
        ./deploy-blog.sh
